<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="2.0" xml:id="id_1" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns1="http://xmlns.oracle.com/cloud/adapter/REST/restyahoo_REQUEST" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/ProxyTwitterYahoo_REQUEST/types" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/REST/restyahoo_REQUEST/types" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:nssrcdfl="http://www.example.org" xmlns:ns2="http://xmlns.oracle.com/cloud/generic/rest/fault/REST/restyahoo" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/twitter/twit/types" xmlns:nstrgdfl="http://xmlns.oracle.com/cloud/generic/rest/fault/twitter/null" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/twitter/twit" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/generic/rest/fault/REST/ProxyTwitterYahoo" xmlns:nsmpr3="http://xmlns.oracle.com/cloud/adapter/REST/ProxyTwitterYahoo_REQUEST" exclude-result-prefixes=" xp20 oraext ns1 xsi nssrcmpr nsmpr0 oracle-xsl-mapper nssrcdfl ns2 xsl fn xsd ora nsmpr2 nsmpr3 ignore01 nsmpr5" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr4="http://xml.oracle.com/types/REST/ProxyTwitterYahoo_REQUEST" xmlns:nsmpr5="http://xmlns.oracle.com/cloud/adapter/REST/restyahoo/types" xmlns:nsmpr6="null">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_875/outbound_449/resourcegroup_781/ProxyTwitterYahoo_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/ProxyTwitterYahoo_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_7">
            <oracle-xsl-mapper:schema location="../../application_113/inbound_123/resourcegroup_883/restyahoo_REQUEST.wsdl" xml:id="id_8"/>
            <oracle-xsl-mapper:rootElement name="executeResponse" namespace="http://xmlns.oracle.com/cloud/adapter/REST/restyahoo_REQUEST/types" xml:id="id_9"/>
            <oracle-xsl-mapper:param name="restyahoo" xml:id="id_10"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source xml:id="id_21"/>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_11">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_12">
            <oracle-xsl-mapper:schema location="../../application_955/inbound_230/resourcegroup_246/twit_REQUEST.wsdl" xml:id="id_13"/>
            <oracle-xsl-mapper:rootElement name="Tweet" namespace="http://xmlns.oracle.com/cloud/adapter/twitter/twit/types" xml:id="id_14"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.2.0.0-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="restyahoo" xml:id="id_17"/>
   <xsl:template match="/" xml:id="id_15">
      <nstrgmpr:Tweet xml:id="id_16">
         
      
      <nstrgmpr:QueryParameters xml:id="id_18">
            <nstrgmpr:status xml:id="id_19">
               
            <xsl:value-of select="concat('Weather  ', /nssrcmpr:execute/nssrcmpr:TemplateParameters/nsmpr4:ciudad, ' : ', $restyahoo/nsmpr0:executeResponse/nsmpr5:response-wrapper/nsmpr5:query/nsmpr5:results/nsmpr5:channel[1.0]/nsmpr5:item/nsmpr5:forecast[1.0]/nsmpr5:text, ' temp max ', $restyahoo/nsmpr0:executeResponse/nsmpr5:response-wrapper/nsmpr5:query/nsmpr5:results/nsmpr5:channel[1.0]/nsmpr5:item/nsmpr5:forecast[1.0]/nsmpr5:high, ' min  ', $restyahoo/nsmpr0:executeResponse/nsmpr5:response-wrapper/nsmpr5:query/nsmpr5:results/nsmpr5:channel[1.0]/nsmpr5:item/nsmpr5:forecast[1.0]/nsmpr5:low)" xml:id="id_20"/>
            </nstrgmpr:status>
         </nstrgmpr:QueryParameters>
      </nstrgmpr:Tweet>
   </xsl:template>
</xsl:stylesheet>
