<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="2.0" xml:id="id_1" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns1="http://xmlns.oracle.com/cloud/adapter/REST/restyahoo_REQUEST" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/ProxyTwitterYahoo_REQUEST/types" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/REST/restyahoo_REQUEST/types" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:nstrgdfl="http://www.example.org" xmlns:ns2="http://xmlns.oracle.com/cloud/generic/rest/fault/REST/restyahoo" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/generic/rest/fault/REST/ProxyTwitterYahoo" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/REST/ProxyTwitterYahoo_REQUEST" exclude-result-prefixes=" xp20 oraext xsi nssrcmpr oracle-xsl-mapper xsl fn xsd ora nsmpr0 nsmpr1 ignore01" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr2="http://xml.oracle.com/types/REST/restyahoo_REQUEST" xmlns:nsmpr3="http://xml.oracle.com/types/REST/ProxyTwitterYahoo_REQUEST">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_875/outbound_449/resourcegroup_781/ProxyTwitterYahoo_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/ProxyTwitterYahoo_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source xml:id="id_16"/>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_113/inbound_123/resourcegroup_883/restyahoo_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/restyahoo_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.1.2.0.0-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:execute xml:id="id_12">
         <nstrgmpr:QueryParameters xml:id="id_13">
            
         <nsmpr2:q xml:id="id_17">
               <xsl:value-of select="concat('select * from weather.forecast where woeid in (select woeid from geo.places where text=&quot;', /nssrcmpr:execute/nssrcmpr:TemplateParameters/nsmpr3:ciudad, ' , ', /nssrcmpr:execute/nssrcmpr:TemplateParameters/nsmpr3:pais, '&quot;)')" xml:id="id_18"/>
            </nsmpr2:q>
            <nsmpr2:format xml:id="id_15">json</nsmpr2:format>
         </nstrgmpr:QueryParameters>
      </nstrgmpr:execute>
   </xsl:template>
</xsl:stylesheet>
